openapi: "3.0.2"
info:
    title: Test Project API
    version: '1.0'
servers:
  - url: http://localhost:5000/
components:
    schemas:
        error:
            type: object
            properties:
                error:
                    description: error message
                    type: string
                    required: true
        history_response:
            type: array
            properties:
                history:
                    description: Massage history
                    type: array
                    required: true


paths:
    /ping:
        get:
            description: Check that server is work
            responses:
                '200':
                    description: OK
                    content:
                        text/plain:
                            schema:
                                title: Server is working
                                type: string
                                example: pong

    /create/message:
        post:
            description: Create message from user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                messageText:
                                    description: Input message text from user
                                    type: string
                                    required: true
                                    default: empty string
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    messageID:
                                        description: Created messages' identificator
                                        type: string
                                        required: true
    /update/message:
        post:
            description: Update message by message id
            parameters:
            - name: messageId
              in: path
              description: message identificator
              required: true
              schema:
                type: string
            responses:
                '200':
                    description: OK
                '400':
                    description: Invalid path parameter
                    content:
                        application/json:
                                schema:
                                    $ref: "#/components/schemas/error"
    /delete/message:
        post:
            description: Delete message by message id
            parameters:
                - name: messageId
                  in: path
                  description: message identificator
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: OK
                '400':
                    description: Invalid path parameter
                    content:
                        application/json:
                                schema:
                                    $ref: "#/components/schemas/error"
    /history/message:
        get:
            description: Get one or more messages history
            requestBody:
                    required: false
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    messageID:
                                        description: one or more messages ids
                                        type: array
                                        required: false
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/history_response"
                '400':
                    description: Invalid one or more message id
                    content:
                        application/json:
                                schema:
                                    $ref: "#/components/schemas/error"
