openapi: "3.0.2"
info:
    title: Test Project API
    version: '1.0'
servers:
  - url: http://localhost:5000/
components:
    schemas:
        error:
            type: object
            properties:
                error:
                    description: error message
                    type: string
                    required: true
                    example: Invalid input
        history:
            type: object
            properties:
                author:
                    description: Username, who make last action with message
                    type: string
                    required: true
                    example: Guts
                messageId:
                    description: message identificator
                    type: string
                    required: true
                    example: 506355c0-5535-4cc2-9700-d67df26da7d9
                action:
                    description: Last action with message
                    type: string
                    required: true
                    enum:
                        - UPDATE
                        - CREATE
                        - DELETE
                    example: CREATE
paths:
    /ping/:
        get:
            description: Check that server is work
            responses:
                '200':
                    description: OK
                    content:
                        text/plain:
                            schema:
                                title: Server is working
                                type: string
                                example: pong

    /message/create:
        post:
            description: Create message from user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                messageText:
                                    description: Input message text from user
                                    type: string
                                    required: true
                                    default:
                        example: {messageText: "This Sword Is The Proof That I Have Lived."}
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    messageID:
                                        description: Created message id
                                        type: string
                                        required: true
                            example: {messageID: "550e8400-e29b-41d4-a716-446655440000"}
    /message/update/{messageID}:
        post:
            description: Update message by message id and save it in history
            parameters:
            - name: messageID
              in: path
              description: message identificator
              required: true
              schema:
                type: string
              example: /update/message/550e8400-e29b-41d4-a716-446655440000
            responses:
                '200':
                    description: OK
                '400':
                    description: Invalid path parameter
                    content:
                        application/json:
                                schema:
                                    $ref: "#/components/schemas/error"
                                example: {error: "Invalid path parameter"}
    /message/delete/{messageId}:
        post:
            description: Delete message by message id and save it in history, after deleting message cant be modify
            parameters:
                - name: messageId
                  in: path
                  description: message identificator
                  required: true
                  schema:
                      type: string
                  example: /delete/message/550e8400-e29b-41d4-a716-446655440000
            responses:
                '200':
                    description: OK
                '400':
                    description: Invalid path parameter
                    content:
                        application/json:
                                schema:
                                    $ref: "#/components/schemas/error"
    /message/history:
        get:
            description: Get one or more messages history
            requestBody:
                    required: false
                    content:
                        application/json:
                            schema:
                                type: array
                                properties:
                                    messageID:
                                        description: Message id for history
                                        type: string
                                        required: true
                            example: [{messageID: 550e8400-e29b-41d4-a716-446655440000}]
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                title: History
                                type: array
                                items:
                                    $ref: "#/components/schemas/history"
                '400':
                    description: Invalid one or more message id
                    content:
                        application/json:
                                schema:
                                    $ref: "#/components/schemas/error"
