"""empty message

Revision ID: ad057dfa009c
Revises: ab43e9ad9d19
Create Date: 2023-11-24 11:41:39.098391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad057dfa009c'
down_revision = 'ab43e9ad9d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_ancestor_id', sa.Integer(), nullable=True))
        batch_op.drop_column('prev_id')
        batch_op.drop_column('next_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('prev_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('message_ancestor_id')

    # ### end Alembic commands ###
